/* Generated by YAKINDU Statechart Tools for Arduino v0.9.0 */

#ifndef ATMEGA_TIMER0_H
#define ATMEGA_TIMER0_H

#define MAX_PARALLEL_TIME_EVENTS 1

#include <avr/sleep.h>
#include <Arduino.h>

#include "sc_types.h"
#include "StatemachineInterface.h"
#include "HardwareConnector.h"
#include "TimerInterface.h"
#include "TimedStatemachineInterface.h"
#include "TimeEvent.h"

class ATmega_Timer0: public TimerInterface {
public:
	ATmega_Timer0(StatemachineInterface* statemachine, HardwareConnector* hardware);
	
	inline ~ATmega_Timer0();
	
	void start();
	
	void setTimer(TimedStatemachineInterface* timedStatemachine, sc_eventid eventId, sc_integer time, sc_boolean isPeriodic);
	
	void unsetTimer(TimedStatemachineInterface* timedStatemachine, sc_eventid eventId);
	
	void runCycle();
	
	void cancel();

private:
	StatemachineInterface* statemachine;
	
	HardwareConnector* hardware;
	
	TimeEvent events[MAX_PARALLEL_TIME_EVENTS];
	
	void init();
	
	void raiseTimeEvents();
	
	void sleep();
};

ATmega_Timer0::~ATmega_Timer0() {
	delete events;
}

#endif /* ATMEGA_TIMER0_H */
