/* Generated by YAKINDU Statechart Tools for Arduino v0.9.0 */

#ifndef TAK_V1_H_
#define TAK_V1_H_


#include "sc_types.h"
#include "StatemachineInterface.h"
#include "TimedStatemachineInterface.h"

/*! \file Header of the state machine 'TAK_v1'.
*/


/*! Define indices of states in the StateConfVector */
#define SCVI_MAIN_REGION_DETECTION 0
#define SCVI_MAIN_REGION_VERIFICATION 0
#define SCVI_MAIN_REGION_SHOOTING 0
#define SCVI_MAIN_REGION_RESET 0


class TAK_v1 : public TimedStatemachineInterface, public StatemachineInterface
{
	public:
		TAK_v1();
		
		virtual ~TAK_v1();
		
		/*! Enumeration of all states */ 
		typedef enum
		{
			TAK_v1_last_state,
			main_region_Detection,
			main_region_Verification,
			main_region_Shooting,
			main_region_Reset
		} TAK_v1States;
					
		static const sc_integer numStates = 4;
		
		//! Inner class for default interface scope.
		class DefaultSCI
		{
			public:
				/*! Gets the value of the variable 'relais' that is defined in the default interface scope. */
				sc_boolean get_relais() const;
				
				/*! Sets the value of the variable 'relais' that is defined in the default interface scope. */
				void set_relais(sc_boolean value);
				
				
				/*! Gets the value of the variable 'servo_deg' that is defined in the default interface scope. */
				sc_integer get_servo_deg() const;
				
				/*! Sets the value of the variable 'servo_deg' that is defined in the default interface scope. */
				void set_servo_deg(sc_integer value);
				
				
				/*! Gets the value of the variable 'vib_measurement' that is defined in the default interface scope. */
				sc_integer get_vib_measurement() const;
				
				/*! Sets the value of the variable 'vib_measurement' that is defined in the default interface scope. */
				void set_vib_measurement(sc_integer value);
				
				
				/*! Raises the in event 'vibration' that is defined in the default interface scope. */
				void raise_vibration(sc_integer value);
				
				
				
			private:
				friend class TAK_v1;
				sc_boolean relais;
				sc_integer servo_deg;
				sc_integer vib_measurement;
				sc_boolean vibration_raised;
				sc_integer vibration_value;
				
				
		};
		
		/*! Returns an instance of the interface class 'DefaultSCI'. */
		DefaultSCI* getDefaultSCI();
		
		/*! Gets the value of the variable 'relais' that is defined in the default interface scope. */
		sc_boolean get_relais() const;
		
		/*! Sets the value of the variable 'relais' that is defined in the default interface scope. */
		void set_relais(sc_boolean value);
		
		/*! Gets the value of the variable 'servo_deg' that is defined in the default interface scope. */
		sc_integer get_servo_deg() const;
		
		/*! Sets the value of the variable 'servo_deg' that is defined in the default interface scope. */
		void set_servo_deg(sc_integer value);
		
		/*! Gets the value of the variable 'vib_measurement' that is defined in the default interface scope. */
		sc_integer get_vib_measurement() const;
		
		/*! Sets the value of the variable 'vib_measurement' that is defined in the default interface scope. */
		void set_vib_measurement(sc_integer value);
		
		/*! Raises the in event 'vibration' that is defined in the default interface scope. */
		void raise_vibration(sc_integer value);
		
		
		/*
		 * Functions inherited from StatemachineInterface
		 */
		virtual void init();
		
		virtual void enter();
		
		virtual void exit();
		
		virtual void runCycle();
		
		/*!
		* Checks if the state machine is active (until 2.4.1 this method was used for states).
		* A state machine is active if it has been entered. It is inactive if it has not been entered at all or if it has been exited.
		*/
		virtual sc_boolean isActive() const;
		
		
		/*!
		* Checks if all active states are final. 
		* If there are no active states then the state machine is considered being inactive. In this case this method returns false.
		*/
		virtual sc_boolean isFinal() const;
		
		/*
		 * Functions inherited from TimedStatemachineInterface
		 */
		virtual void setTimer(TimerInterface* timerInterface);
		
		virtual TimerInterface* getTimer();
		
		virtual void raiseTimeEvent(sc_eventid event);
		
		virtual sc_integer getNumberOfParallelTimeEvents();
		
		/*! Checks if the specified state is active (until 2.4.1 the used method for states was calles isActive()). */
		sc_boolean isStateActive(TAK_v1States state) const;
		
		//! number of time events used by the state machine.
		static const sc_integer timeEventsCount = 3;
		
		//! number of time events that can be active at once.
		static const sc_integer parallelTimeEventsCount = 1;
		
		
	protected:
		
		
	private:
		TAK_v1(const TAK_v1 &rhs);
		TAK_v1& operator=(const TAK_v1&);
		
		
		//! the maximum number of orthogonal states defines the dimension of the state configuration vector.
		static const sc_ushort maxOrthogonalStates = 1;
		
		TimerInterface* timer;
		sc_boolean timeEvents[timeEventsCount];
		
		
		TAK_v1States stateConfVector[maxOrthogonalStates];
		
		sc_ushort stateConfVectorPosition;
		
		DefaultSCI iface;
		
		// prototypes of all internal functions
		
		sc_boolean check_main_region__choice_0_tr0_tr0();
		void effect_main_region__choice_0_tr0();
		void effect_main_region__choice_0_tr1();
		void enact_main_region_Verification();
		void enact_main_region_Shooting();
		void enact_main_region_Reset();
		void exact_main_region_Verification();
		void exact_main_region_Shooting();
		void exact_main_region_Reset();
		void enseq_main_region_Detection_default();
		void enseq_main_region_Verification_default();
		void enseq_main_region_Shooting_default();
		void enseq_main_region_Reset_default();
		void enseq_main_region_default();
		void exseq_main_region_Detection();
		void exseq_main_region_Verification();
		void exseq_main_region_Shooting();
		void exseq_main_region_Reset();
		void exseq_main_region();
		void react_main_region__choice_0();
		void react_main_region__entry_Default();
		sc_boolean react();
		sc_boolean main_region_Detection_react(const sc_boolean try_transition);
		sc_boolean main_region_Verification_react(const sc_boolean try_transition);
		sc_boolean main_region_Shooting_react(const sc_boolean try_transition);
		sc_boolean main_region_Reset_react(const sc_boolean try_transition);
		void clearInEvents();
		void clearOutEvents();
		
		
		
		
};




#endif /* TAK_V1_H_ */
