/* Generated by YAKINDU Statechart Tools for Arduino v0.9.0 */

#include "ArduinoMain.h"
#include "ATmega_Timer0.h"
#include "../src/TAK_v1Connector.h"

TAK_v1* statemachine;
TAK_v1Connector* connector;
ATmega_Timer0* timer;

TAK_v1* getStatemachine() {
	return statemachine;
}

void setup() {
	statemachine = new TAK_v1();
	connector = new TAK_v1Connector(statemachine);
	timer = new ATmega_Timer0(statemachine, connector);

	statemachine->setTimer(timer);
	timer->start();
}

void loop() {
	timer->runCycle();
}
