/* Generated by YAKINDU Statechart Tools for Arduino v0.9.0 */

#ifndef ARDUINOMAIN_H
#define ARDUINOMAIN_H

#include <Arduino.h>
#include "TAK_v1.h"

TAK_v1* getStatemachine();

#endif /* ARDUINOMAIN_H */
